server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: DinoAuction

  activemq:
      broker-url: tcp://localhost:61616
      user: ${ACTIVEMQ_USER}
      password: ${ACTIVEMQ_PASSWORD}